# Site settings

title: Erick Chang
email: ekc.dev@gmail.com # Your contant email

description: I work as an Android Developer. Sometimes I like to write about it.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.ekchang.com" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:     ekchang  # Replace this with your Twitter username
github_username:      ekchang  # Replace this with your GitHub username
linkedin_username:    ekchang  # Replace this with your LinkedIn username
stackoverflow_username: 4546572/ekchang
google_plus_username:   # Replace this with your Google+ username
facebook_username:      # Replace this with your Facebook username
dribbble_username:      # Replace this with your Dribbble username

# Build settings
markdown: kramdown
